// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/google/uuid"
	"go-boilerplate/internal/domain"
	"sync"
)

// Ensure, that AuthUseCaseMock does implement domain.AuthUseCase.
// If this is not the case, regenerate this file with moq.
var _ domain.AuthUseCase = &AuthUseCaseMock{}

// AuthUseCaseMock is a mock implementation of domain.AuthUseCase.
//
//	func TestSomethingThatUsesAuthUseCase(t *testing.T) {
//
//		// make and configure a mocked domain.AuthUseCase
//		mockedAuthUseCase := &AuthUseCaseMock{
//			ChangePasswordFunc: func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
//				panic("mock out the ChangePassword method")
//			},
//			ForgotPasswordFunc: func(ctx context.Context, email string) error {
//				panic("mock out the ForgotPassword method")
//			},
//			LoginFunc: func(ctx context.Context, email string, password string) (*domain.Auth, error) {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func(ctx context.Context, userID uuid.UUID) error {
//				panic("mock out the Logout method")
//			},
//			RefreshTokenFunc: func(ctx context.Context, refreshToken string) (*domain.Auth, error) {
//				panic("mock out the RefreshToken method")
//			},
//			RegisterFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Register method")
//			},
//			ResetPasswordFunc: func(ctx context.Context, email string, token string, newPassword string) error {
//				panic("mock out the ResetPassword method")
//			},
//		}
//
//		// use mockedAuthUseCase in code that requires domain.AuthUseCase
//		// and then make assertions.
//
//	}
type AuthUseCaseMock struct {
	// ChangePasswordFunc mocks the ChangePassword method.
	ChangePasswordFunc func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error

	// ForgotPasswordFunc mocks the ForgotPassword method.
	ForgotPasswordFunc func(ctx context.Context, email string) error

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, email string, password string) (*domain.Auth, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, userID uuid.UUID) error

	// RefreshTokenFunc mocks the RefreshToken method.
	RefreshTokenFunc func(ctx context.Context, refreshToken string) (*domain.Auth, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, user *domain.User) error

	// ResetPasswordFunc mocks the ResetPassword method.
	ResetPasswordFunc func(ctx context.Context, email string, token string, newPassword string) error

	// calls tracks calls to the methods.
	calls struct {
		// ChangePassword holds details about calls to the ChangePassword method.
		ChangePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// CurrentPassword is the currentPassword argument value.
			CurrentPassword string
			// NewPassword is the newPassword argument value.
			NewPassword string
		}
		// ForgotPassword holds details about calls to the ForgotPassword method.
		ForgotPassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// RefreshToken holds details about calls to the RefreshToken method.
		RefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// ResetPassword holds details about calls to the ResetPassword method.
		ResetPassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Token is the token argument value.
			Token string
			// NewPassword is the newPassword argument value.
			NewPassword string
		}
	}
	lockChangePassword sync.RWMutex
	lockForgotPassword sync.RWMutex
	lockLogin          sync.RWMutex
	lockLogout         sync.RWMutex
	lockRefreshToken   sync.RWMutex
	lockRegister       sync.RWMutex
	lockResetPassword  sync.RWMutex
}

// ChangePassword calls ChangePasswordFunc.
func (mock *AuthUseCaseMock) ChangePassword(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
	if mock.ChangePasswordFunc == nil {
		panic("AuthUseCaseMock.ChangePasswordFunc: method is nil but AuthUseCase.ChangePassword was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserID          uuid.UUID
		CurrentPassword string
		NewPassword     string
	}{
		Ctx:             ctx,
		UserID:          userID,
		CurrentPassword: currentPassword,
		NewPassword:     newPassword,
	}
	mock.lockChangePassword.Lock()
	mock.calls.ChangePassword = append(mock.calls.ChangePassword, callInfo)
	mock.lockChangePassword.Unlock()
	return mock.ChangePasswordFunc(ctx, userID, currentPassword, newPassword)
}

// ChangePasswordCalls gets all the calls that were made to ChangePassword.
// Check the length with:
//
//	len(mockedAuthUseCase.ChangePasswordCalls())
func (mock *AuthUseCaseMock) ChangePasswordCalls() []struct {
	Ctx             context.Context
	UserID          uuid.UUID
	CurrentPassword string
	NewPassword     string
} {
	var calls []struct {
		Ctx             context.Context
		UserID          uuid.UUID
		CurrentPassword string
		NewPassword     string
	}
	mock.lockChangePassword.RLock()
	calls = mock.calls.ChangePassword
	mock.lockChangePassword.RUnlock()
	return calls
}

// ForgotPassword calls ForgotPasswordFunc.
func (mock *AuthUseCaseMock) ForgotPassword(ctx context.Context, email string) error {
	if mock.ForgotPasswordFunc == nil {
		panic("AuthUseCaseMock.ForgotPasswordFunc: method is nil but AuthUseCase.ForgotPassword was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockForgotPassword.Lock()
	mock.calls.ForgotPassword = append(mock.calls.ForgotPassword, callInfo)
	mock.lockForgotPassword.Unlock()
	return mock.ForgotPasswordFunc(ctx, email)
}

// ForgotPasswordCalls gets all the calls that were made to ForgotPassword.
// Check the length with:
//
//	len(mockedAuthUseCase.ForgotPasswordCalls())
func (mock *AuthUseCaseMock) ForgotPasswordCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockForgotPassword.RLock()
	calls = mock.calls.ForgotPassword
	mock.lockForgotPassword.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *AuthUseCaseMock) Login(ctx context.Context, email string, password string) (*domain.Auth, error) {
	if mock.LoginFunc == nil {
		panic("AuthUseCaseMock.LoginFunc: method is nil but AuthUseCase.Login was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Password string
	}{
		Ctx:      ctx,
		Email:    email,
		Password: password,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, email, password)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedAuthUseCase.LoginCalls())
func (mock *AuthUseCaseMock) LoginCalls() []struct {
	Ctx      context.Context
	Email    string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Password string
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *AuthUseCaseMock) Logout(ctx context.Context, userID uuid.UUID) error {
	if mock.LogoutFunc == nil {
		panic("AuthUseCaseMock.LogoutFunc: method is nil but AuthUseCase.Logout was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, userID)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedAuthUseCase.LogoutCalls())
func (mock *AuthUseCaseMock) LogoutCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// RefreshToken calls RefreshTokenFunc.
func (mock *AuthUseCaseMock) RefreshToken(ctx context.Context, refreshToken string) (*domain.Auth, error) {
	if mock.RefreshTokenFunc == nil {
		panic("AuthUseCaseMock.RefreshTokenFunc: method is nil but AuthUseCase.RefreshToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RefreshToken string
	}{
		Ctx:          ctx,
		RefreshToken: refreshToken,
	}
	mock.lockRefreshToken.Lock()
	mock.calls.RefreshToken = append(mock.calls.RefreshToken, callInfo)
	mock.lockRefreshToken.Unlock()
	return mock.RefreshTokenFunc(ctx, refreshToken)
}

// RefreshTokenCalls gets all the calls that were made to RefreshToken.
// Check the length with:
//
//	len(mockedAuthUseCase.RefreshTokenCalls())
func (mock *AuthUseCaseMock) RefreshTokenCalls() []struct {
	Ctx          context.Context
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		RefreshToken string
	}
	mock.lockRefreshToken.RLock()
	calls = mock.calls.RefreshToken
	mock.lockRefreshToken.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *AuthUseCaseMock) Register(ctx context.Context, user *domain.User) error {
	if mock.RegisterFunc == nil {
		panic("AuthUseCaseMock.RegisterFunc: method is nil but AuthUseCase.Register was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, user)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedAuthUseCase.RegisterCalls())
func (mock *AuthUseCaseMock) RegisterCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// ResetPassword calls ResetPasswordFunc.
func (mock *AuthUseCaseMock) ResetPassword(ctx context.Context, email string, token string, newPassword string) error {
	if mock.ResetPasswordFunc == nil {
		panic("AuthUseCaseMock.ResetPasswordFunc: method is nil but AuthUseCase.ResetPassword was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Email       string
		Token       string
		NewPassword string
	}{
		Ctx:         ctx,
		Email:       email,
		Token:       token,
		NewPassword: newPassword,
	}
	mock.lockResetPassword.Lock()
	mock.calls.ResetPassword = append(mock.calls.ResetPassword, callInfo)
	mock.lockResetPassword.Unlock()
	return mock.ResetPasswordFunc(ctx, email, token, newPassword)
}

// ResetPasswordCalls gets all the calls that were made to ResetPassword.
// Check the length with:
//
//	len(mockedAuthUseCase.ResetPasswordCalls())
func (mock *AuthUseCaseMock) ResetPasswordCalls() []struct {
	Ctx         context.Context
	Email       string
	Token       string
	NewPassword string
} {
	var calls []struct {
		Ctx         context.Context
		Email       string
		Token       string
		NewPassword string
	}
	mock.lockResetPassword.RLock()
	calls = mock.calls.ResetPassword
	mock.lockResetPassword.RUnlock()
	return calls
}
