// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/google/uuid"
	"go-boilerplate/internal/domain"
	"sync"
)

// Ensure, that UserUseCaseMock does implement domain.UserUseCase.
// If this is not the case, regenerate this file with moq.
var _ domain.UserUseCase = &UserUseCaseMock{}

// UserUseCaseMock is a mock implementation of domain.UserUseCase.
//
//	func TestSomethingThatUsesUserUseCase(t *testing.T) {
//
//		// make and configure a mocked domain.UserUseCase
//		mockedUserUseCase := &UserUseCaseMock{
//			CreateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.User, error) {
//				panic("mock out the GetByID method")
//			},
//			GetMeFunc: func(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
//				panic("mock out the GetMe method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserUseCase in code that requires domain.UserUseCase
//		// and then make assertions.
//
//	}
type UserUseCaseMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *domain.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.User, error)

	// GetMeFunc mocks the GetMe method.
	GetMeFunc func(ctx context.Context, userID uuid.UUID) (*domain.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user *domain.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetMe holds details about calls to the GetMe method.
		GetMe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
	}
	lockCreate  sync.RWMutex
	lockDelete  sync.RWMutex
	lockGetByID sync.RWMutex
	lockGetMe   sync.RWMutex
	lockList    sync.RWMutex
	lockUpdate  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserUseCaseMock) Create(ctx context.Context, user *domain.User) error {
	if mock.CreateFunc == nil {
		panic("UserUseCaseMock.CreateFunc: method is nil but UserUseCase.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserUseCase.CreateCalls())
func (mock *UserUseCaseMock) CreateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserUseCaseMock) Delete(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("UserUseCaseMock.DeleteFunc: method is nil but UserUseCase.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserUseCase.DeleteCalls())
func (mock *UserUseCaseMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserUseCaseMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserUseCaseMock.GetByIDFunc: method is nil but UserUseCase.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserUseCase.GetByIDCalls())
func (mock *UserUseCaseMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetMe calls GetMeFunc.
func (mock *UserUseCaseMock) GetMe(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	if mock.GetMeFunc == nil {
		panic("UserUseCaseMock.GetMeFunc: method is nil but UserUseCase.GetMe was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetMe.Lock()
	mock.calls.GetMe = append(mock.calls.GetMe, callInfo)
	mock.lockGetMe.Unlock()
	return mock.GetMeFunc(ctx, userID)
}

// GetMeCalls gets all the calls that were made to GetMe.
// Check the length with:
//
//	len(mockedUserUseCase.GetMeCalls())
func (mock *UserUseCaseMock) GetMeCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetMe.RLock()
	calls = mock.calls.GetMe
	mock.lockGetMe.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserUseCaseMock) List(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
	if mock.ListFunc == nil {
		panic("UserUseCaseMock.ListFunc: method is nil but UserUseCase.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserUseCase.ListCalls())
func (mock *UserUseCaseMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserUseCaseMock) Update(ctx context.Context, user *domain.User) error {
	if mock.UpdateFunc == nil {
		panic("UserUseCaseMock.UpdateFunc: method is nil but UserUseCase.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserUseCase.UpdateCalls())
func (mock *UserUseCaseMock) UpdateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
