// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"go-boilerplate/internal/auth"
	"go-boilerplate/internal/domain"
	"sync"
)

// Ensure, that AuthServiceMock does implement auth.AuthService.
// If this is not the case, regenerate this file with moq.
var _ auth.AuthService = &AuthServiceMock{}

// AuthServiceMock is a mock implementation of auth.AuthService.
//
//	func TestSomethingThatUsesAuthService(t *testing.T) {
//
//		// make and configure a mocked auth.AuthService
//		mockedAuthService := &AuthServiceMock{
//			CheckPasswordFunc: func(password string, hash string) error {
//				panic("mock out the CheckPassword method")
//			},
//			GenerateAuthResponseFunc: func(user *domain.User) (*domain.Auth, error) {
//				panic("mock out the GenerateAuthResponse method")
//			},
//			HashPasswordFunc: func(password string) (string, error) {
//				panic("mock out the HashPassword method")
//			},
//			ValidateAccessTokenFunc: func(tokenString string) (*domain.Claims, error) {
//				panic("mock out the ValidateAccessToken method")
//			},
//		}
//
//		// use mockedAuthService in code that requires auth.AuthService
//		// and then make assertions.
//
//	}
type AuthServiceMock struct {
	// CheckPasswordFunc mocks the CheckPassword method.
	CheckPasswordFunc func(password string, hash string) error

	// GenerateAuthResponseFunc mocks the GenerateAuthResponse method.
	GenerateAuthResponseFunc func(user *domain.User) (*domain.Auth, error)

	// HashPasswordFunc mocks the HashPassword method.
	HashPasswordFunc func(password string) (string, error)

	// ValidateAccessTokenFunc mocks the ValidateAccessToken method.
	ValidateAccessTokenFunc func(tokenString string) (*domain.Claims, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckPassword holds details about calls to the CheckPassword method.
		CheckPassword []struct {
			// Password is the password argument value.
			Password string
			// Hash is the hash argument value.
			Hash string
		}
		// GenerateAuthResponse holds details about calls to the GenerateAuthResponse method.
		GenerateAuthResponse []struct {
			// User is the user argument value.
			User *domain.User
		}
		// HashPassword holds details about calls to the HashPassword method.
		HashPassword []struct {
			// Password is the password argument value.
			Password string
		}
		// ValidateAccessToken holds details about calls to the ValidateAccessToken method.
		ValidateAccessToken []struct {
			// TokenString is the tokenString argument value.
			TokenString string
		}
	}
	lockCheckPassword        sync.RWMutex
	lockGenerateAuthResponse sync.RWMutex
	lockHashPassword         sync.RWMutex
	lockValidateAccessToken  sync.RWMutex
}

// CheckPassword calls CheckPasswordFunc.
func (mock *AuthServiceMock) CheckPassword(password string, hash string) error {
	if mock.CheckPasswordFunc == nil {
		panic("AuthServiceMock.CheckPasswordFunc: method is nil but AuthService.CheckPassword was just called")
	}
	callInfo := struct {
		Password string
		Hash     string
	}{
		Password: password,
		Hash:     hash,
	}
	mock.lockCheckPassword.Lock()
	mock.calls.CheckPassword = append(mock.calls.CheckPassword, callInfo)
	mock.lockCheckPassword.Unlock()
	return mock.CheckPasswordFunc(password, hash)
}

// CheckPasswordCalls gets all the calls that were made to CheckPassword.
// Check the length with:
//
//	len(mockedAuthService.CheckPasswordCalls())
func (mock *AuthServiceMock) CheckPasswordCalls() []struct {
	Password string
	Hash     string
} {
	var calls []struct {
		Password string
		Hash     string
	}
	mock.lockCheckPassword.RLock()
	calls = mock.calls.CheckPassword
	mock.lockCheckPassword.RUnlock()
	return calls
}

// GenerateAuthResponse calls GenerateAuthResponseFunc.
func (mock *AuthServiceMock) GenerateAuthResponse(user *domain.User) (*domain.Auth, error) {
	if mock.GenerateAuthResponseFunc == nil {
		panic("AuthServiceMock.GenerateAuthResponseFunc: method is nil but AuthService.GenerateAuthResponse was just called")
	}
	callInfo := struct {
		User *domain.User
	}{
		User: user,
	}
	mock.lockGenerateAuthResponse.Lock()
	mock.calls.GenerateAuthResponse = append(mock.calls.GenerateAuthResponse, callInfo)
	mock.lockGenerateAuthResponse.Unlock()
	return mock.GenerateAuthResponseFunc(user)
}

// GenerateAuthResponseCalls gets all the calls that were made to GenerateAuthResponse.
// Check the length with:
//
//	len(mockedAuthService.GenerateAuthResponseCalls())
func (mock *AuthServiceMock) GenerateAuthResponseCalls() []struct {
	User *domain.User
} {
	var calls []struct {
		User *domain.User
	}
	mock.lockGenerateAuthResponse.RLock()
	calls = mock.calls.GenerateAuthResponse
	mock.lockGenerateAuthResponse.RUnlock()
	return calls
}

// HashPassword calls HashPasswordFunc.
func (mock *AuthServiceMock) HashPassword(password string) (string, error) {
	if mock.HashPasswordFunc == nil {
		panic("AuthServiceMock.HashPasswordFunc: method is nil but AuthService.HashPassword was just called")
	}
	callInfo := struct {
		Password string
	}{
		Password: password,
	}
	mock.lockHashPassword.Lock()
	mock.calls.HashPassword = append(mock.calls.HashPassword, callInfo)
	mock.lockHashPassword.Unlock()
	return mock.HashPasswordFunc(password)
}

// HashPasswordCalls gets all the calls that were made to HashPassword.
// Check the length with:
//
//	len(mockedAuthService.HashPasswordCalls())
func (mock *AuthServiceMock) HashPasswordCalls() []struct {
	Password string
} {
	var calls []struct {
		Password string
	}
	mock.lockHashPassword.RLock()
	calls = mock.calls.HashPassword
	mock.lockHashPassword.RUnlock()
	return calls
}

// ValidateAccessToken calls ValidateAccessTokenFunc.
func (mock *AuthServiceMock) ValidateAccessToken(tokenString string) (*domain.Claims, error) {
	if mock.ValidateAccessTokenFunc == nil {
		panic("AuthServiceMock.ValidateAccessTokenFunc: method is nil but AuthService.ValidateAccessToken was just called")
	}
	callInfo := struct {
		TokenString string
	}{
		TokenString: tokenString,
	}
	mock.lockValidateAccessToken.Lock()
	mock.calls.ValidateAccessToken = append(mock.calls.ValidateAccessToken, callInfo)
	mock.lockValidateAccessToken.Unlock()
	return mock.ValidateAccessTokenFunc(tokenString)
}

// ValidateAccessTokenCalls gets all the calls that were made to ValidateAccessToken.
// Check the length with:
//
//	len(mockedAuthService.ValidateAccessTokenCalls())
func (mock *AuthServiceMock) ValidateAccessTokenCalls() []struct {
	TokenString string
} {
	var calls []struct {
		TokenString string
	}
	mock.lockValidateAccessToken.RLock()
	calls = mock.calls.ValidateAccessToken
	mock.lockValidateAccessToken.RUnlock()
	return calls
}
