// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"go-boilerplate/pkg/redis"
	"sync"
	"time"
)

// Ensure, that RedisClientMock does implement redis.RedisClient.
// If this is not the case, regenerate this file with moq.
var _ redis.RedisClient = &RedisClientMock{}

// RedisClientMock is a mock implementation of redis.RedisClient.
//
//	func TestSomethingThatUsesRedisClient(t *testing.T) {
//
//		// make and configure a mocked redis.RedisClient
//		mockedRedisClient := &RedisClientMock{
//			DelFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Del method")
//			},
//			GetFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value interface{}, ttl int) error {
//				panic("mock out the Set method")
//			},
//			TTLFunc: func(ctx context.Context, key string) (time.Duration, error) {
//				panic("mock out the TTL method")
//			},
//		}
//
//		// use mockedRedisClient in code that requires redis.RedisClient
//		// and then make assertions.
//
//	}
type RedisClientMock struct {
	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (string, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value interface{}, ttl int) error

	// TTLFunc mocks the TTL method.
	TTLFunc func(ctx context.Context, key string) (time.Duration, error)

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value interface{}
			// TTL is the ttl argument value.
			TTL int
		}
		// TTL holds details about calls to the TTL method.
		TTL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
	}
	lockDel sync.RWMutex
	lockGet sync.RWMutex
	lockSet sync.RWMutex
	lockTTL sync.RWMutex
}

// Del calls DelFunc.
func (mock *RedisClientMock) Del(ctx context.Context, key string) error {
	if mock.DelFunc == nil {
		panic("RedisClientMock.DelFunc: method is nil but RedisClient.Del was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	return mock.DelFunc(ctx, key)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedRedisClient.DelCalls())
func (mock *RedisClientMock) DelCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RedisClientMock) Get(ctx context.Context, key string) (string, error) {
	if mock.GetFunc == nil {
		panic("RedisClientMock.GetFunc: method is nil but RedisClient.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedisClient.GetCalls())
func (mock *RedisClientMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *RedisClientMock) Set(ctx context.Context, key string, value interface{}, ttl int) error {
	if mock.SetFunc == nil {
		panic("RedisClientMock.SetFunc: method is nil but RedisClient.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value interface{}
		TTL   int
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedisClient.SetCalls())
func (mock *RedisClientMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value interface{}
	TTL   int
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value interface{}
		TTL   int
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// TTL calls TTLFunc.
func (mock *RedisClientMock) TTL(ctx context.Context, key string) (time.Duration, error) {
	if mock.TTLFunc == nil {
		panic("RedisClientMock.TTLFunc: method is nil but RedisClient.TTL was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockTTL.Lock()
	mock.calls.TTL = append(mock.calls.TTL, callInfo)
	mock.lockTTL.Unlock()
	return mock.TTLFunc(ctx, key)
}

// TTLCalls gets all the calls that were made to TTL.
// Check the length with:
//
//	len(mockedRedisClient.TTLCalls())
func (mock *RedisClientMock) TTLCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockTTL.RLock()
	calls = mock.calls.TTL
	mock.lockTTL.RUnlock()
	return calls
}
