// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/google/uuid"
	"go-boilerplate/internal/domain"
	"sync"
)

// Ensure, that UserRepositoryMock does implement domain.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ domain.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of domain.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked domain.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*domain.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.User, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByRefreshTokenFunc: func(ctx context.Context, refreshToken string) (*domain.User, error) {
//				panic("mock out the GetByRefreshToken method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Update method")
//			},
//			UpdateRefreshTokenFunc: func(ctx context.Context, id uuid.UUID, refreshToken string) error {
//				panic("mock out the UpdateRefreshToken method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires domain.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *domain.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*domain.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.User, error)

	// GetByRefreshTokenFunc mocks the GetByRefreshToken method.
	GetByRefreshTokenFunc func(ctx context.Context, refreshToken string) (*domain.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user *domain.User) error

	// UpdateRefreshTokenFunc mocks the UpdateRefreshToken method.
	UpdateRefreshTokenFunc func(ctx context.Context, id uuid.UUID, refreshToken string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByRefreshToken holds details about calls to the GetByRefreshToken method.
		GetByRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// UpdateRefreshToken holds details about calls to the UpdateRefreshToken method.
		UpdateRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
	}
	lockCount              sync.RWMutex
	lockCreate             sync.RWMutex
	lockDelete             sync.RWMutex
	lockGetByEmail         sync.RWMutex
	lockGetByID            sync.RWMutex
	lockGetByRefreshToken  sync.RWMutex
	lockList               sync.RWMutex
	lockUpdate             sync.RWMutex
	lockUpdateRefreshToken sync.RWMutex
}

// Count calls CountFunc.
func (mock *UserRepositoryMock) Count(ctx context.Context) (int, error) {
	if mock.CountFunc == nil {
		panic("UserRepositoryMock.CountFunc: method is nil but UserRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedUserRepository.CountCalls())
func (mock *UserRepositoryMock) CountCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, user *domain.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryMock.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepository.DeleteCalls())
func (mock *UserRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepositoryMock) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepositoryMock.GetByEmailFunc: method is nil but UserRepository.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetByEmailCalls())
func (mock *UserRepositoryMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserRepositoryMock.GetByIDFunc: method is nil but UserRepository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserRepository.GetByIDCalls())
func (mock *UserRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByRefreshToken calls GetByRefreshTokenFunc.
func (mock *UserRepositoryMock) GetByRefreshToken(ctx context.Context, refreshToken string) (*domain.User, error) {
	if mock.GetByRefreshTokenFunc == nil {
		panic("UserRepositoryMock.GetByRefreshTokenFunc: method is nil but UserRepository.GetByRefreshToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RefreshToken string
	}{
		Ctx:          ctx,
		RefreshToken: refreshToken,
	}
	mock.lockGetByRefreshToken.Lock()
	mock.calls.GetByRefreshToken = append(mock.calls.GetByRefreshToken, callInfo)
	mock.lockGetByRefreshToken.Unlock()
	return mock.GetByRefreshTokenFunc(ctx, refreshToken)
}

// GetByRefreshTokenCalls gets all the calls that were made to GetByRefreshToken.
// Check the length with:
//
//	len(mockedUserRepository.GetByRefreshTokenCalls())
func (mock *UserRepositoryMock) GetByRefreshTokenCalls() []struct {
	Ctx          context.Context
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		RefreshToken string
	}
	mock.lockGetByRefreshToken.RLock()
	calls = mock.calls.GetByRefreshToken
	mock.lockGetByRefreshToken.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
	if mock.ListFunc == nil {
		panic("UserRepositoryMock.ListFunc: method is nil but UserRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepository.ListCalls())
func (mock *UserRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(ctx context.Context, user *domain.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateRefreshToken calls UpdateRefreshTokenFunc.
func (mock *UserRepositoryMock) UpdateRefreshToken(ctx context.Context, id uuid.UUID, refreshToken string) error {
	if mock.UpdateRefreshTokenFunc == nil {
		panic("UserRepositoryMock.UpdateRefreshTokenFunc: method is nil but UserRepository.UpdateRefreshToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ID           uuid.UUID
		RefreshToken string
	}{
		Ctx:          ctx,
		ID:           id,
		RefreshToken: refreshToken,
	}
	mock.lockUpdateRefreshToken.Lock()
	mock.calls.UpdateRefreshToken = append(mock.calls.UpdateRefreshToken, callInfo)
	mock.lockUpdateRefreshToken.Unlock()
	return mock.UpdateRefreshTokenFunc(ctx, id, refreshToken)
}

// UpdateRefreshTokenCalls gets all the calls that were made to UpdateRefreshToken.
// Check the length with:
//
//	len(mockedUserRepository.UpdateRefreshTokenCalls())
func (mock *UserRepositoryMock) UpdateRefreshTokenCalls() []struct {
	Ctx          context.Context
	ID           uuid.UUID
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		ID           uuid.UUID
		RefreshToken string
	}
	mock.lockUpdateRefreshToken.RLock()
	calls = mock.calls.UpdateRefreshToken
	mock.lockUpdateRefreshToken.RUnlock()
	return calls
}
